package Domain;

import net.lemnik.eodsql.AutoGeneratedKeys;
import net.lemnik.eodsql.GeneratedKeys;
import net.lemnik.eodsql.ResultColumn;
import net.lemnik.eodsql.Update;

public class User {

    @AutoGeneratedKeys
    @ResultColumn(value = "id")
    private int id;
    private String username;
    private String password;
    private long dateCreated;
    private int gamesPlayed;
    private int currentStreak;
    private int longestStreak;

    public User(String username, String password, long dateCreated) {
        this.username = username;
        this.password = password;
        this.dateCreated = dateCreated;
        gamesPlayed = 0;
        currentStreak = 0;
        longestStreak = 0;
    }

    public User() {
        gamesPlayed = 0;
        currentStreak = 0;
        longestStreak = 0;
    }

    public void addGamePlayed(boolean win) {
        gamesPlayed++;
        if (win)
            currentStreak++;
        else currentStreak = 0;

        if (currentStreak > longestStreak)
            longestStreak = currentStreak;
    }
    public int getId() {
        return id;
    }

    @AutoGeneratedKeys
    public void setId(int id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public long getDateCreated() {
        return dateCreated;
    }

    public void setDateCreated(long dateCreated) {
        this.dateCreated = dateCreated;
    }

    public int getTotalGamesPlayed() {
        return gamesPlayed;
    }

    public void setTotalGamesPlayed(int gamesPlayed) {
        this.gamesPlayed = gamesPlayed;
    }

    public int getCurrentStreak() {
        return currentStreak;
    }

    public void setCurrentStreak(int currentStreak) {
        this.currentStreak = currentStreak;
    }

    public int getLongestStreak() {
        return longestStreak;
    }

    public void setLongestStreak(int longestStreak) {
        this.longestStreak = longestStreak;
    }

}
